
export enum JwtErrorCode {
    REQUEST_UNDEFINED = 'REQUEST_UNDEFINED',
    REQUEST_HEADER_UNDEFINED = 'REQUEST_HEADER_UNDEFINED',

    TOKEN_STALE = 'TOKEN_STALE',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_UNDEFINED = 'TOKEN_UNDEFINED',
    TOKEN_WRONG_ISS = 'TOKEN_WRONG_ISS',
    TOKEN_WRONG_TYPE = 'TOKEN_WRONG_TYPE',
    TOKEN_WRONG_AUDIENCE = 'TOKEN_WRONG_AUDIENCE',
    TOKEN_WRONG_CLIENT_ID = 'TOKEN_WRONG_CLIENT_ID',

    TOKEN_ROLE_FORBIDDEN = 'TOKEN_ROLE_FORBIDDEN',
    TOKEN_ROLE_INVALID_TYPE = 'TOKEN_ROLE_INVALID_TYPE',
    TOKEN_RESOURCE_INVALID = 'TOKEN_RESOURCE_INVALID',
    TOKEN_RESOURCE_FORBIDDEN = 'TOKEN_RESOURCE_FORBIDDEN',
    TOKEN_RESOURCE_SCOPE_FORBIDDEN = 'TOKEN_RESOURCE_SCOPE_FORBIDDEN',

    TOKEN_NOT_ACTIVE = 'TOKEN_NOT_ACTIVE',
    TOKEN_NOT_SIGNED = 'TOKEN_NOT_SIGNED',
    TOKEN_INVALID_SIGNATURE = 'TOKEN_INVALID_SIGNATURE',
}
